In [1]:
# The charts are made using Plotly and Cufflinks. You need to set it up first for the code to run properly.
# https://plot.ly/ipython-notebooks/cufflinks/

# The code below has not been polished/optimized yet.

#Import libraries used
%matplotlib inline
#import pyfolio as pf
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go
import pandas as pd

import pandas_datareader as pdr
import datetime
import numpy as np
import cufflinks as cf
#cf.go_offline()
cf.go_online()
import matplotlib.pyplot as plt

In [2]:
# Analyze rolling returns

def rollingReturns(series, days):
    collector = []
    for i in range(len(series)):
        if i+days >= len(series):
            collector.append(np.NaN)
            continue
        collector.append((series.iloc[i+days,5]/series.iloc[i,5])-1)
    return collector

start = datetime.datetime(1993, 1, 1)
end = datetime.datetime(2017, 3, 3)

spy = pdr.get_data_yahoo('SPY',start=start, end=end)
spy["1yr rolling return"] = rollingReturns(spy,365)
spy["2yr rolling return"] = rollingReturns(spy,730)
spy["3yr rolling return"] = rollingReturns(spy,1095)
spy["4yr rolling return"] = rollingReturns(spy,1460)
spy["5yr rolling return"] = rollingReturns(spy,1825)
spy["6yr rolling return"] = rollingReturns(spy,2190)
spy

,Open,High,Low,Close,Volume,Adj Close,1yr rolling return,2yr rolling return,3yr rolling return,4yr rolling return,5yr rolling return,6yr rolling return
Date,,,,,,,,,,,,
1993-01-29,43.968700,43.968700,43.750000,43.937500,1003200,27.879550,0.058516,0.501320,1.136540,1.903570,2.746634,1.823484
1993-02-01,43.968700,44.250000,43.968700,44.250000,480500,28.077839,0.052873,0.476269,1.112109,1.875114,2.679755,1.788543
1993-02-02,44.218700,44.375000,44.125000,44.343700,201300,28.137295,0.061985,0.480737,1.100655,1.849996,2.824440,1.844628
1993-02-03,44.406200,44.843700,44.375000,44.812500,529400,28.434761,0.051236,0.470504,1.076372,1.817041,2.741725,1.858527
1993-02-04,44.968700,45.093700,44.468700,45.000000,531500,28.553735,0.048658,0.471481,1.075376,1.832667,2.713815,1.833677
1993-02-05,44.968700,45.062500,44.718700,44.968700,492100,28.533875,0.047225,0.471755,1.117424,1.855764,2.693330,1.830470
1993-02-08,44.968700,45.125000,44.906200,44.968700,596100,28.533875,0.042535,0.470259,1.128149,1.855764,2.743446,1.848338
1993-02-09,44.812500,44.812500,44.562500,44.656200,122100,28.335585,0.052011,0.482431,1.149598,1.893082,2.694345,1.807250
1993-02-10,44.656200,44.750000,44.531200,44.718700,379600,28.375243,0.052353,0.496161,1.151600,1.914215,2.602792,1.797336
1993-02-11,44.781200,45.125000,44.781200,44.937500,19500,28.514077,0.048673,0.492995,1.182521,1.921949,2.612314,1.781902
1993-02-12,44.875000,44.875000,44.593700,44.593700,42500,28.295927,0.055666,0.490168,1.217887,2.013906,2.684281,1.858712
1993-02-16,44.468700,44.468700,43.406200,43.468700,374800,27.582083,0.082987,0.525638,1.276082,2.072482,2.751243,1.917695
1993-02-17,43.468700,43.531200,43.281200,43.437500,210900,27.562286,0.086006,0.532544,1.274544,2.074689,2.723880,1.912016
1993-02-18,43.937500,43.937500,42.812500,43.406200,378100,27.542425,0.097623,0.507294,1.268248,2.099602,2.642507,1.966431
1993-02-19,43.406200,43.562500,43.343700,43.562500,34900,27.641602,0.098898,0.482190,1.283436,2.001254,2.712372,1.949105
1993-02-22,43.687500,43.781200,43.562500,43.718700,513600,27.740715,0.096455,0.485745,1.267527,2.029160,2.739202,1.862120
1993-02-23,43.843700,43.875000,43.468700,43.687500,373700,27.720918,0.097609,0.484495,1.214129,2.022463,2.806555,1.829779
1993-02-24,43.718700,44.250000,43.718700,44.250000,26300,28.077839,0.077427,0.462582,1.241474,1.934745,2.794545,1.784333
1993-02-25,44.218700,44.375000,44.125000,44.343700,44500,28.137295,0.071492,0.477324,1.221140,2.005508,2.746999,1.849618
1993-02-26,44.437500,44.437500,44.187500,44.406200,66200,28.176953,0.072541,0.470698,1.207111,2.015540,2.695811,1.865013
1993-03-01,44.562500,44.562500,44.218700,44.281200,66500,28.097637,0.077399,0.479788,1.221931,2.010543,2.648081,1.910707
1993-03-02,44.312500,44.937500,44.250000,44.937500,182400,28.514077,0.065634,0.467911,1.174859,1.972057,2.567738,1.912770
1993-03-03,45.000000,45.156200,44.937500,45.125000,280100,28.633051,0.057252,0.462184,1.191112,1.916434,2.500594,1.896796
1993-03-04,45.187500,45.187500,44.875000,44.875000,89500,28.474419,0.071454,0.473703,1.239541,1.938563,2.577489,1.922017
1993-03-05,44.937500,45.125000,44.718700,44.750000,40000,28.395103,0.074086,0.489850,1.276709,1.861859,2.525931,1.933301
1993-03-08,44.843700,45.750000,44.843700,45.750000,50800,29.029631,0.058051,0.452138,1.204267,1.871594,2.452772,1.851622
1993-03-09,45.656200,45.687500,45.500000,45.593700,169300,28.930454,0.060966,0.469660,1.234958,1.877579,2.577585,1.925762
1993-03-10,45.593700,45.687500,45.406200,45.687500,194400,28.989973,0.055239,0.472534,1.205769,1.917492,2.578069,1.922559
1993-03-11,45.718700,45.843700,45.500000,45.562500,70900,28.910657,0.057421,0.489129,1.221687,1.937927,2.650693,1.935944
1993-03-12,45.187500,45.218700,44.812500,45.093700,643600,28.613190,0.067337,0.520279,1.252453,2.009958,2.752899,1.953296
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-01-20,226.699997,227.309998,225.970001,226.740005,129168600,225.757861,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-23,226.740005,226.809998,225.270004,226.149994,75061600,225.170405,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-24,226.399994,228.080002,226.270004,227.600006,95555300,226.614136,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-25,228.699997,229.570007,228.509995,229.570007,84437700,228.575604,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-26,229.399994,229.710007,229.009995,229.330002,59970700,228.336639,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-27,229.419998,229.589996,228.759995,228.970001,59711100,227.978197,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-30,228.169998,228.199997,226.410004,227.550003,79737300,226.564350,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-31,226.979996,227.600006,226.320007,227.529999,75880800,226.544432,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-01,227.529999,228.589996,226.940002,227.619995,79117700,226.634039,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-02,227.619995,228.100006,226.820007,227.770004,69657600,226.783398,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-03,228.820007,229.550003,228.460007,229.339996,80563200,228.346590,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-06,228.869995,229.330002,228.539993,228.929993,57790100,227.938362,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-07,229.380005,229.660004,228.720001,228.940002,57931200,227.948329,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-08,228.940002,229.389999,228.309998,229.240005,51566200,228.247032,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-09,229.240005,230.949997,229.240005,230.600006,65955200,229.601142,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-10,231.000000,231.770004,230.619995,231.509995,66015900,230.507188,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-13,232.080002,233.070007,232.050003,232.770004,55182100,231.761740,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-14,232.559998,233.710007,232.160004,233.699997,71109000,232.687705,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-15,233.449997,235.139999,233.389999,234.919998,86785800,233.902421,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-16,234.949997,235.160004,233.850006,234.720001,84722400,233.703291,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-17,233.949997,235.089996,233.929993,235.089996,77204100,234.071683,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-21,235.520004,236.690002,235.509995,236.490005,88946100,235.465628,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-22,236.020004,236.539993,235.830002,236.279999,62115200,235.256531,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-23,236.880005,236.899994,235.559998,236.440002,74615900,235.415842,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-24,235.460007,236.789993,235.410004,236.740005,82381600,235.714545,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-27,236.639999,237.309998,236.350006,237.110001,56515400,236.082938,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-28,236.669998,236.949997,236.020004,236.470001,96961900,235.445710,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-01,238.389999,240.320007,238.369995,239.779999,149158200,238.741370,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-02,239.559998,239.570007,238.210007,238.270004,70246000,237.237917,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-03,238.169998,238.610001,237.729996,238.419998,81974300,237.387261,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
## Make a rolling period returns chart using plotly

figure = spy[[str(x) + "yr rolling return" for  x in range(1,7)]].iplot(yTitle='Rolling Period Return', title='Analysis of Rolling Period Returns',
        subplots=True, subplot_titles=[str(x) + " Yr Rolling Return" for  x in range(1,7)], shape=(3,2),  asFigure=True)

#shared_yaxes=True,
for x in range(1,7):
    figure["layout"]["yaxis"+str(x)]["range"] = [-0.5,3]    
    
figure["layout"]["legend"]["orientation"] = "h"
#figure["layout"]["height"] =900 
#figure["layout"]["width"] =900


py.iplot(figure)

The draw time for this plot will be slow for clients without much RAM.

/Users/davidkoh/anaconda/envs/tradingroom/lib/python3.6/site-packages/plotly/api/v1/clientresp.py:40: UserWarning:

Estimated Draw Time Slow

In [4]:
# 1 year rolling return chart using plotly
figure = spy[[str(x) + "yr rolling return" for  x in range(1,2)]].iplot(
    yTitle='Rolling Period Return', title='Analysis of Rolling Period Returns')
        
figure

In [5]:
#Box PLot of Rolling Period Returns
rolling_periods = [str(x) + "yr rolling return" for  x in range(1,7)]

spy[rolling_periods].iplot(kind="box")

In [6]:
# Calculating percentage of investing days are profitable after a number of years
def calculatePercentage(df):
    rolling_periods = [str(x) + "yr rolling return" for  x in range(1,7)]
    resultDict ={}
    for period in rolling_periods:
        
        series = df[period]
        maxgain = max(series)
        maxloss = min(series)
        ProportionNegativeReturns = len(series[series<=0])/series.count()
        fifthpercentile = series.quantile(q=0.05)
        twentyfifthpercentile = series.quantile(q=0.25)
        median = series.quantile(q=0.5)
        seventyfithpercentile = series.quantile(q=0.75)
        LessThanNegative10 = len(series[series<=-0.10])/series.count()
        MoreThanPositive10 = len(series[series>=0.10])/series.count()
        
     
        result = [maxgain,maxloss,ProportionNegativeReturns,fifthpercentile,twentyfifthpercentile,median,
                  seventyfithpercentile,LessThanNegative10,MoreThanPositive10]
        
        resultDict[period] = result
        
    resultDF = pd.DataFrame.from_dict(resultDict,orient="index")
    resultDF.columns = [
        "Max Gain", "Max Loss", "Proportion of Negative Returns", "5th Percentile","25th Percentile","Median",
        "75th Percentile", "Proportion of Less than -10% Returns","Proportion of More Than +10% Returns"
    ]
    return (resultDF)


        
ss = calculatePercentage(spy)
ss

,Max Gain,Max Loss,Proportion of Negative Returns,5th Percentile,25th Percentile,Median,75th Percentile,Proportion of Less than -10% Returns,Proportion of More Than +10% Returns
1yr rolling return,0.663939,-0.536828,0.207435,-0.262999,0.049502,0.191975,0.327175,0.158162,0.647203
2yr rolling return,1.297250,-0.446436,0.238104,-0.304139,0.018964,0.371073,0.603666,0.192581,0.701948
3yr rolling return,2.273028,-0.344583,0.273075,-0.185942,-0.027046,0.380739,0.954518,0.174140,0.640861
4yr rolling return,2.744159,-0.191284,0.092665,-0.037497,0.112443,0.279129,1.035291,0.007812,0.771050
5yr rolling return,2.972648,-0.337861,0.046194,0.039079,0.258767,0.465330,0.787003,0.026161,0.914919
6yr rolling return,2.124548,-0.466682,0.077875,-0.196459,0.461421,0.715097,0.982074,0.059825,0.894533

In [7]:
### Generating cumulative return chart of SPY

(spy.iloc[:,5]/spy.iloc[0,5]).iplot(title="SPY ETF's Cumulative Returns Since Inception", yTitle="Cumulative Returns")